column_width = 80
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferDouble"
collapse_simple_statement = "Never"
call_parentheses = "Always"

[sort_requires]
enabled = false
